# Generated by Django 4.2.7 on 2023-11-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canicrossy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='athlete',
            name='dog_race',
            field=models.CharField(default='', max_length=200, verbose_name='chien race'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='athlete',
            name='dog_name',
            field=models.CharField(max_length=200, verbose_name='chien nom'),
        ),
    ]
