# Generated by Django 4.2.7 on 2023-11-24 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canicrossy', '0006_alter_participant_race_number_alter_participant_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('race', models.CharField(blank=True, max_length=200, null=True, verbose_name='race')),
                ('ident', models.CharField(max_length=200, verbose_name='ident')),
            ],
            options={
                'verbose_name': 'chien',
                'verbose_name_plural': 'chiens',
            },
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='dog_ident',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='dog_name',
        ),
        migrations.RemoveField(
            model_name='athlete',
            name='dog_race',
        ),
        migrations.AddField(
            model_name='participant',
            name='dog',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='canicrossy.dog', verbose_name='chien'),
            preserve_default=False,
        ),
    ]
