# Generated by Django 4.2.7 on 2023-11-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canicrossy', '0008_alter_participant_options_alter_participant_dog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='delay',
            field=models.CharField(default='00:00', max_length=5, verbose_name='délai (mm:ss)'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='time',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='chrono (mm:ss)'),
        ),
    ]
