# Generated by Django 4.2.7 on 2023-11-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canicrossy', '0009_alter_participant_delay_alter_participant_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nom')),
                ('date', models.DateField(verbose_name='date')),
                ('location', models.CharField(max_length=200, verbose_name='lieu')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
            },
        ),
        migrations.RemoveField(
            model_name='dog',
            name='race',
        ),
        migrations.RemoveField(
            model_name='race',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='race',
            name='city',
        ),
        migrations.RemoveField(
            model_name='race',
            name='date',
        ),
        migrations.AddField(
            model_name='dog',
            name='event',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='event'),
        ),
        migrations.AddField(
            model_name='race',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canicrossy.event', verbose_name='evenement'),
        ),
    ]
