# Generated by Django 4.2.7 on 2023-11-26 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canicrossy', '0010_event_remove_dog_race_remove_race_categories_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'evenement', 'verbose_name_plural': 'evenements'},
        ),
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.RemoveField(
            model_name='dog',
            name='event',
        ),
        migrations.AddField(
            model_name='dog',
            name='race',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='race'),
        ),
    ]
