# Generated by Django 4.2.7 on 2023-11-26 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('canicrossy', '0011_alter_event_options_alter_race_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='race',
            options={'verbose_name': 'course', 'verbose_name_plural': 'courses'},
        ),
    ]
