# Generated by Django 4.2.7 on 2023-11-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canicrossy', '0012_alter_race_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='categories',
            field=models.ManyToManyField(to='canicrossy.category'),
        ),
    ]
