# Generated by Django 4.2.7 on 2023-12-01 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('canicrossy', '0013_race_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athlete',
            name='federation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='canicrossy.federation'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='license',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='num license'),
        ),
    ]
